name: Docker Build

on:
  push:
    branches: [ master ]

jobs:
  build-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Latest
      run: |
        docker build . --file Dockerfile --tag rdeavila/kafka-manager-docker:latest
        docker push rdeavila/kafka-manager-docker:latest
